stages:
  - build
  - test
  - deploy
    
build_job:
  stage: build
  script:
   - 'dotnet restore'
   - 'dotnet build --configuration Release'
  artifacts:
    paths:
      - SharpenSkills.Logic/bin/


test_job:
  stage: test
  script:
    - 'dotnet test --configuration Release'

deploy_job:
  stage: deploy
  dependencies:
    - build_job
  script:
    - dotnet nuget push SharpenSkills.Logic\bin\Release\*.nupkg --source VegaNuget




    