
stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - '& "$env:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe" /p:Configuration=Release'

