
  
stages:
  - build
  - test

    
build_job:
  stage: build
  script:
   - 'dotnet restore'
   - 'dotnet build'


test_job:
  stage: test
  script:
    - dotnet test --no-build -c Release -v n SharpenSkills.Tests\SharpenSkills.Tests.csproj --logger "trx;LogFileName=testreport.trx"
  after_script:
        - trx2junit src\SharpenSkills.Tests\Testresults\testreport.trx 
  artifacts:
        reports:
            junit: SharpenSkills.Tests\Testresults\testreport.xml