stages:
  - build
  - test
    
build_job:
  stage: build
  script:
   - 'dotnet restore'
   - 'dotnet build'

test_job:
  stage: test
  script:
    - 'dotnet test'
  artifacts:
    reports:
      junit: report.xml



    