stages:
  - build
  - test
  - deploy
    
build_job:
  stage: build
  script:
   - 'dotnet restore'
   - 'dotnet build --configuration Release --no-incremental'


test_job:
  stage: test
  script:
    - 'dotnet test'

deploy_job:
  stage: deploy
  script:
    - dotnet nuget push "$CI_BUILDS_DIR\AT3yZQ7Z\0\n.kajzer\sharpen-your-skills-assignment\SharpenSkills.Logic\bin\Release\*.nupkg" --source VegaNuget    



    