variables:
  MSBUILD_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe'
  buildConfiguration: 'Release'
  
stages:
  - build
  - test
  - deploy

    
build_job:
  stage: build
  script: dotnet build --configuration Release

