
  
stages:
  - build
  - test

    
build_job:
  stage: build
  script:
   - 'dotnet restore'
   - 'dotnet build'

test_job:
  stage: test
  script:
    - '"C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" "SharpenSkills.Tests\bin\Release"'

