stages:
  - build
  - test
  - deploy
    
build_job:
  stage: build
  script:
   - 'dotnet restore'
   - 'dotnet build ./SharpenSkills.Logic/SharpenSkills.Logic.csproj --configuration Release --no-incremental'


test_job:
  stage: test
  script:
    - 'dotnet test'

deploy_job:
  stage: deploy
  script:
    - dotnet nuget push C:\gitlab\builds\AT3yZQ7Z\0\n.kajzer\sharpen-your-skills-assignment\SharpenSkills.Logic\bin\Release\SharpenSkills.Logic.1.0.0.nupkg --source VegaNuget    



    