variables:
  EXE_RELEASE_FOLDER: 'SharpenSkills.Logic\bin\Release'
  MSI_RELEASE_FOLDER: 'Setup\bin\Release'
  TEST_FOLDER: 'SharpenSkills.Tests\bin\Release'
  NUGET_PATH: 'C:\Program Files (x86)\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\MSBuild\15.0\Bin\msbuild.exe'
  NUNIT_PATH: 'C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe'

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release'  # build the project


