stages:
  - build
  - test
  - deploy
    
build_job:
  stage: build
  script:
   - 'dotnet restore'
   - 'dotnet build --configuration Release'
  artifacts:
    paths:
      - SharpenSkills.Logic/bin/


test_job:
  stage: test
  script:
    - 'dotnet test --configuration Release'

deploy_job:
  stage: deploy
  dependencies:
    - build_job
  script:
    - dotnet nuget push "$CI_BUILDS_DIR\AT3yZQ7Z\0\n.kajzer\sharpen-your-skills-assignment\SharpenSkills.Logic\bin\Release\SharpenSkills.Logic.1.0.0.nupkg" --source VegaNuget    



    