stages:
  - build
  - test
    
build_job:
  stage: build
  script:
   - 'dotnet restore'
   - 'msbuild ./SharpenSkills.Logic/SharpenSkills.Logic.csproj /t:pack /p:Configuration=Release'

test_job:
  stage: test
  script:
    - 'dotnet test'



    