
  
stages:
  - build
  - test

    
build_job:
  stage: build
  script:
   - 'dotnet restore'
   - 'dotnet build'


test_job:
  stage: test
  script:
    - dotnet test --no-build -c Debug -r $CI_PROJECT_DIR/cobertura -v n SharpenSkills.Tests\SharpenSkills.Tests.csproj --logger "junit;LogFilePath=$CI_PROJECT_DIR/junit/junit-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
  artifacts:
    paths:
      - SharpenSkills.Tests/coverage.cobertura.xml
      - SharpenSkills.Tests/junit-test-result.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: SharpenSkills.Tests/coverage.cobertura.xml
      junit:
        - SharpenSkills.Tests/junit-test-result.xml

    