stages:
  - build
  - test
    
build_job:
  stage: build
  script:
   - 'dotnet restore'
   - 'dotnet build'
   - 'nuget restore'
   - 'dotnet pack'

test_job:
  stage: test
  script:
    - 'dotnet test'



    