stages:
  - build
  - test
    
build_job:
  stage: build
  script:
   - 'dotnet restore'
   - 'dotnet build'
   - 'dotnet pack ./SharpenSkills.Logic/SharpenSkills.Logic.csproj'

test_job:
  stage: test
  script:
    - 'dotnet test'



    