variables:
  MSBUILD_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe'
  
stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release'

