variables:
  MSBUILD_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe'
  
stages:
  - build

before_script:
  - 'C:\Nuget\nuget.exe restore SharpenSkills.sln'
    
build_job:
  stage: build
  script: ls

