stages:
  - build
  - test
  - deploy
    
build_job:
  stage: build
  script:
   - 'dotnet restore'
   - 'dotnet build ./SharpenSkills.Logic/SharpenSkills.Logic.csproj --configuration Release'
   - 'dotnet pack ./SharpenSkills.Logic/SharpenSkills.Logic.csproj --no-build --configuration Release'

test_job:
  stage: test
  script:
    - 'dotnet test'

deploy_job:
  stage: deploy
  script:
    - cd $CI_BUILDS_DIR\AT3yZQ7Z\0\n.kajzer\
    - cd sharpen-your-skills-assignment
    - cd SharpenSkills.Logic
    - ls
    - cd bin
    - cd Release
    - dotnet nuget push "$CI_BUILDS_DIR\AT3yZQ7Z\0\n.kajzer\sharpen-your-skills-assignment\SharpenSkills.Logic\bin\Release\*.nupkg" --source VegaNuget    



    