variables:
  EXE_RELEASE_FOLDER: 'SharpenSkills.Logic\bin\Release'
  MSI_RELEASE_FOLDER: 'Setup\bin\Release'
  TEST_FOLDER: 'SharpenSkills.Tests\bin\Release'
  NUGET_PATH: 'C:\Program Files (x86)\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\MSBuild\15.0\Bin\msbuild.exe'
  NUNIT_PATH: 'C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe'

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  only:
    - tags  # the build process will only be started by git tag commits
  script:
    - '& "$env:NUGET_PATH" restore'  # restore Nuget dependencies
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release'  # build the project
  artifacts:
    expire_in: 1 week  # save gitlab server space, we copy the files we need to deploy folder later on
    paths:
      - '$env:EXE_RELEASE_FOLDER\SharpenSkills.exe'  # saving exe to copy to deploy folder
      - '$env:MSI_RELEASE_FOLDER\SharpenSkills Setup.msi'  # saving msi to copy to deploy folder
      - '$env:TEST_FOLDER\'  # saving entire Test project so NUnit can run tests

test_job:
  stage: test
  only:
    - tags
  script:
    - '& "$env:NUNIT_PATH" ".\$env:TEST_FOLDER\SharpenSkills.Tests.dll"'  # running NUnit tests
  artifacts:
    when: always  # save test results even when the task fails
    expire_in: 1 week  # save gitlab server space, we copy the files we need to deploy folder later on
    paths:
      - '.\TestResult.xml'  # saving NUnit results to copy to deploy folder
  dependencies:
    - build_job