stages:
  - build
  - test
  - deploy
    
build_job:
  stage: build
  script:
   - 'dotnet restore'
   - 'dotnet build ./SharpenSkills.Logic/SharpenSkills.Logic.csproj --configuration Release'

test_job:
  stage: test
  script:
    - 'dotnet test'

deploy_job:
  stage: deploy
  script:
    - dotnet nuget push "./SharpenSkills.Logic/Packages/*.nupkg" --source gitlab




    